# Generated by Django 5.0 on 2024-03-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('cover_image', models.CharField(blank=True, max_length=200, verbose_name='Cover Image')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Average Rating')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
        migrations.CreateModel(
            name='DestinationAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_information', models.TextField(blank=True, verbose_name='Weather Information')),
                ('historical_and_cultural_significance', models.TextField(blank=True, verbose_name='Historical and Cultural Significance')),
                ('language_support', models.TextField(blank=True, verbose_name='Language Support')),
                ('travel_tips_and_recommendations', models.TextField(blank=True, verbose_name='Travel Tips and Recommendations')),
                ('social_media_links', models.TextField(blank=True, verbose_name='Social Media Links')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='Destination.destination')),
            ],
            options={
                'verbose_name': 'Destination Additional Info',
                'verbose_name_plural': 'Destination Additional Info',
            },
        ),
        migrations.CreateModel(
            name='DestinationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_hours', models.CharField(blank=True, max_length=200, verbose_name='Operating Hours')),
                ('entry_fees', models.CharField(blank=True, max_length=100, verbose_name='Entry Fees')),
                ('nearby_accommodations', models.TextField(blank=True, verbose_name='Nearby Accommodations')),
                ('accessibility_features', models.TextField(blank=True, verbose_name='Accessibility Features')),
                ('facilities_and_amenities', models.TextField(blank=True, verbose_name='Facilities and Amenities')),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='Destination.destination')),
            ],
            options={
                'verbose_name': 'Destination Detail',
                'verbose_name_plural': 'Destination Details',
            },
        ),
        migrations.CreateModel(
            name='TransportationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Bus', 'Bus'), ('Train', 'Train'), ('Plane', 'Plane'), ('Car', 'Car'), ('Boat', 'Boat')], max_length=20, verbose_name='Transportation Option')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation_options', to='Destination.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Transportation Option',
                'verbose_name_plural': 'Transportation Options',
            },
        ),
    ]
