# Generated by Django 5.0 on 2024-03-09 13:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 9, 13, 11, 44, 256073, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='destinationadditionalinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 9, 13, 11, 52, 611724, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationadditionalinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='destinationdetails',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 9, 13, 11, 55, 857181, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destinationdetails',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='transportationoption',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 9, 13, 11, 59, 274752, tzinfo=datetime.timezone.utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportationoption',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('image', models.ImageField(upload_to='destination_images/', verbose_name='Image')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Destination.destination')),
            ],
            options={
                'verbose_name': 'Destination Image',
                'verbose_name_plural': 'Destination Images',
            },
        ),
    ]
