# Generated by Django 5.0 on 2024-03-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_destination_created_destination_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinationadditionalinfo',
            options={'verbose_name': 'Additional Info', 'verbose_name_plural': 'Additional Info'},
        ),
        migrations.AlterModelOptions(
            name='destinationdetails',
            options={'verbose_name': 'Detail', 'verbose_name_plural': 'Details'},
        ),
        migrations.AlterModelOptions(
            name='destinationimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='transportationoption',
            options={'verbose_name': 'Transportation', 'verbose_name_plural': 'Transportations'},
        ),
    ]
