# Generated by Django 5.0 on 2024-05-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0003_alter_destinationadditionalinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
