# Generated by Django 5.0 on 2024-05-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0004_alter_destination_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='cover_image',
            field=models.ImageField(upload_to='destination_images/covers', verbose_name='Cover Image'),
        ),
    ]
