# Generated by Django 4.1.3 on 2024-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0007_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='galery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Galery'),
        ),
        migrations.AddField(
            model_name='destinationimage',
            name='galery',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Galery'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/covers', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images/', verbose_name='Image'),
        ),
    ]
