# Generated by Django 5.0 on 2024-05-05 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Destination', '0005_alter_destination_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('number_of_persons', models.IntegerField(verbose_name='Number of Persons')),
                ('category', models.IntegerField(verbose_name='Category')),
                ('special_request', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('special_accommodation', models.CharField(choices=[('none', 'No Special Accommodation Required'), ('wheelchair', 'Wheelchair Access Required'), ('visual', 'Visual Assistance Required'), ('hearing', 'Hearing Assistance Required'), ('other', 'Other (Please Specify in Special Requests)')], default='none', max_length=100, verbose_name='Special Accommodation Needs')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Destination.destination', verbose_name='Destination')),
            ],
            options={
                'verbose_name': 'Tour Booking',
                'verbose_name_plural': 'Tour Bookings',
            },
        ),
    ]
