# Generated by Django 5.0 on 2024-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourBouking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='category',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='number_of_kids',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of Kids'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='number_of_persons',
            field=models.IntegerField(blank=True, default=1, verbose_name='Number of Persons'),
        ),
    ]
