# Generated by Django 5.0 on 2024-03-09 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Destination', '0003_alter_destinationadditionalinfo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('profile_picture_url', models.ImageField(blank=True, upload_to='profile_pictures/', verbose_name='Profile Picture URL')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook Profile')),
                ('favorite_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by', to='Destination.destination', verbose_name='Favorite Destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
