# Generated by Django 5.0 on 2024-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('description', models.TextField(verbose_name='Company Description')),
                ('address', models.CharField(max_length=255, verbose_name='Company Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('about_us', models.TextField(blank=True, verbose_name='About Us')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Page URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Handle URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram Page URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Page URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube Channel URL')),
            ],
        ),
    ]
