# Generated by Django 5.0 on 2024-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmConfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='website',
            field=models.CharField(default='www.travela.com', max_length=255, verbose_name='Company Address'),
        ),
    ]
