# Generated by Django 5.0 on 2024-05-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmConfig', '0002_companyinfo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Subject')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('shelter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contact', to='tourizmConfig.companyinfo')),
            ],
        ),
    ]
