# Generated by Django 5.0 on 2024-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmConfig', '0003_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='shelter',
            new_name='company',
        ),
    ]
