# Generated by Django 5.0 on 2024-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmConfig', '0004_rename_shelter_contactmessage_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Email News Letter',
                'verbose_name_plural': 'Email News Letters',
            },
        ),
    ]
